apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd
  labels:
    app: argocd
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
        - name: argocd
          image: ${REGISTRY}/${APP}:${BUILD_ID}
          ports:
            - containerPort: 5005
          envFrom:
          - configMapRef:
              name: argocd-env-config
          resources:
            requests:
              memory: 1024Mi
              cpu: 250m
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: dockerhub